config/routes.rb
Rails.application.routes.draw do
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", simple_pages_about_path %></li>
        <li><%= link_to "Contact", simple_pages_contact_path %></li>
      </ul>
    </nav>

    <%= yield %>

    <footer>
      &copy; 2018 Bike Berlin
    </footer>

  </body>
</html>

app/views/simple_pages/about.html.erb
<h1>About</h1>
<p>Not sure what the application is for.</p>

app/views/simple_pages/contact.html.erb
<h1>Contact</h1>
<p>We are always happy to help in any way we can.</p>
<p>You can reach us at: 1-800-WE-HEAR-U (1-800-934-3278)</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>